import type { AppRuntime } from "@vibeos/shared";

export function runtimeGuide(runtime: AppRuntime): string {
  return `[PREPARED INTERACTION AND MOTION]
Prepare a few likely next interactions in THIS generation, alongside the visible screen. Tabs, expandable details, menus, filters and sorting should respond locally without another model call. Keep the first view compact; do not generate an entire branch tree. Prepared content is presentation only: NEVER pre-execute writes, notifications or business actions.
Declarative controls use data-vibeos-local='<JSON>' (no executable expressions):
- {"action":"select","target":"views","value":"agenda"}: panels carry data-vibeos-group="views" data-vibeos-panel="agenda"; other panels in the group hide. Controls carry the same local JSON. Give inactive panels hidden initially. The runtime sets aria-selected="true|false" on controls: style the active control using [aria-selected="true"], NEVER a fixed active class or inline selected colors. Use role="tab" inside role="tablist" for keyboard navigation.
- {"action":"show|hide|toggle","target":"detail"}: targets carry data-vibeos-local-id="detail". hidden controls initial visibility. Use a close button with hide; popups stay inside this app.
- {"action":"filter","target":"records"}: put it on a search input. Target has data-vibeos-local-id="records" and children data-vibeos-item with optional data-vibeos-search text. Filtering uses actual current items.
- {"action":"sort","target":"records","direction":"asc|desc"}: children use data-vibeos-sort for sorting.
Only the six listed local actions exist. For an AI business action use <button type="button" data-vibeos-action="generate-plan">Generate plan</button> or <button type="button" data-vibeos-action="complete-task" data-id="actual-record-id">Complete</button>. NEVER put act, AI calls or writes in data-vibeos-local. Prefer these ordinary AI controls for generation, business mutations, file processing and export; keep JavaScript focused on continuous/local presentation rather than hand-coding the whole app.
Native <details data-vibeos-local-id="stable-id"><summary>...</summary>...</details> also expands locally and preserves its open state. A summary revealing shared record data must carry data-vibeos-prefetch="true" and an AI fallback data-vibeos-action/data-id, just like other prepared record controls. Keep business buttons separate from summary.
Local actions may also carry data-vibeos-action as an AI fallback. Mark a control data-vibeos-prefetch="true" ONLY when it reveals prepared record content that depends on shared data; stale prepared content falls back to AI. Do not mark purely structural tabs/menus. Preserve local targets and scripts in unchanged regions.
CSS: a small <style> INSIDE your root/region is allowed. Use scoped classes, :hover/:focus-visible, transitions and @keyframes. Choose purposeful motion (feedback, reveal, progress), honor prefers-reduced-motion, and retain VibeOS tokens/fonts. Never globally restyle html/body or load external CSS/fonts. The host owns the theme.
${runtime === "interactive" ? `[INTERACTIVE RUNTIME v1]
THIS application version explicitly supports JavaScript in an isolated window. Only use inert blocks <script type="application/vibeos" data-vibeos-script="stable-id">BODY</script> inside the smallest region they own. Max 8 blocks / 64 KiB total. Plain scripts, inline on* handlers, external modules and network access are prohibited. The host validates first and only then mounts scripts; no scripts run in streaming previews.
BODY is a JavaScript function body with parameters vibe and root (owning region element). It may return a cleanup function. Each block has its OWN function scope: helpers/variables from another block are not visible. Use root.querySelector directly or define helpers in each owning block. Never wrap the body in another uncalled function. JavaScript can update this region's view/Canvas, never the OS shell. Use stable local attributes and delegation so AI region updates remain compatible.
vibe API:
- state(): current serializable LOCAL view state. setState({...patch}): merge and persist view-only fields (16 KiB). Include timer deadlines, selected records and local sort settings so rerenders do not reset them. Persist on meaningful transitions (start/pause/reset), not every animation frame or timer tick. Derive the live display from the saved deadline. Business data stays in app-data.
- on(event, selector, handler): delegated listener on root; handler(event, matchedElement). It consumes the event so it does not ALSO call AI. Use this for local actions. Removed on region replacement.
- interval(fn, ms), timeout(fn, ms), frame(fn): tracked timers/animation frame; auto-cleaned on replacement/close and suspended while minimized. For repeated animation schedule frame again. Deadlines use Date.now(), never count timer ticks.
- onUpdate(fn): receives updates after DOM patches. onData(fn): receives data-mode system/app deliveries (including appData). Return cleanup or use vibe.signal for any manually registered resources.
- act(action, data?): explicitly ask the live AI to handle a semantic action. Current view state and actual form values accompany it. Do not implement an independent chatbot.
- command(command): Promise of the ACTUAL response using the existing APP COMMUNICATION protocol. Use request/responseMode:data for system services; handle rejection visibly. Example inside an async handler: await vibe.command({action:'request',target:{system:'app-data'},topic:'get',responseMode:'data'}). For set, send returned version and complete changed data; never fake success. Cross-app AI work still uses mode:ai and replies only after confirmed completion. The script body itself is synchronous; use async handlers or promise chains, never top-level await.
Files, notifications, app/window actions must use system bridges or vibe.act; never fetch(), eval(), import(), localStorage, parent DOM, window.open or alerts. Other apps are reached by communication identities, not JavaScript globals. Loading a script must not mutate real data. Empty/loading/error states and a visible data-mode error are required when work is asynchronous. Keep shared data bindings/refreshes independent of purely local view state.
Example: <script type="application/vibeos" data-vibeos-script="clock">const end=vibe.state().deadline||Date.now()+60000; vibe.setState({deadline:end}); vibe.interval(()=>{root.querySelector('[data-clock]').textContent=String(Math.max(0,Math.ceil((end-Date.now())/1000)));},250);</script>` : "[HTML RUNTIME]\nThis version remains script-free. Use prepared declarative controls, CSS motion and the existing AI/communication actions. Never emit script blocks. Upgrading JavaScript requires a new interactive application version."}`;
}
